version: "3.9"
services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: chronos
      MARIADB_USER: chronos
      MARIADB_PASSWORD: chronos
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    command: flask --app app run --debug --host 0.0.0.0 --port 8000
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mariadb+mariadbconnector://chronos:chronos@db:3306/chronos
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db_data:
